apiVersion: v1
kind: Service
metadata:
  name: hello-python-port
spec:
  type: NodePort
  ports:
    - port: 6000
      targetPort: 5000
      nodePort: 31500
  selector:
    component: flaskapp
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-python
  labels: 
    component: flaskapp
spec:
  containers:
  - name: hello-python
    image: chrissamharris/hello-python:latest
    ports:
    - containerPort: 5000